### ISSUE TITLE
Reboot loop, Win8.1 target

### ISSUE THREAD

**Issue by bklockwood** [bklockwood/PSWU#45]
This was intended as a validation test for release 1.3. See #30 . 

The first round of 204 updates applies fine. 
The second round, 14 updates, installs 'with errors'.
The third round, 1 update, fails to install (2:51:20), and an erroneous log entry (2:51:21) says updates were installed.
The failed upgrade is: Upgrade to Windows 10 Pro, version 1511, 10586. 
Script runs again without reboot. 1 update found and installed. Calls for reboot (2:51:34) 40
Script reboots system ~147 times over the next ~2 hours. 
Script then finds two updates  and halts after finding the system in a pending reboot state.

I _suspect_ the issue is that the Win10 upgrade is now marked 'recommended' and so gets past the -SkipOptional flag. Cannot verify from the log that I have, though.

Here's the log:

```
PS C:\Users\bryanda\Documents\GitHub\PSWU> get-winevent -ComputerName t81 -logname pswu | sort recordid |ft recordid, timecreated, ID, Providername, message -AutoSize  

RecordId TimeCreated          Id ProviderName       Message                                                                           
-------- -----------          -- ------------       -------                                                                           
       1 3/12/2016 9:00:31 AM  2 Install-AllUpdates Starting locally with params: -Computername t81 -SkipOptional -Verbose  ...       
       2 3/12/2016 9:03:19 AM 52 Get-UpdateList     211 update(s) found in 44 seconds.                                                
       3 3/12/2016 9:03:21 AM  6 Install-AllUpdates 204 update(s) will be installed. ...                                              
       4 3/12/2016 9:03:23 AM 27 Install-Update     204 eligible updates found. ...                                                   
       5 3/12/2016 9:51:36 AM 29 Install-Update     Downloaded successfully; beginning install of 204 updates                         
       6 3/12/2016 1:49:21 PM 31 Install-Update     Installed updates successfully.                                                   
       7 3/12/2016 1:49:22 PM 33 Install-Update     Updates installed; please reboot soon.                                            
       8 3/12/2016 1:49:22 PM  7 Install-AllUpdates Returning to start.                                                               
       9 3/12/2016 1:49:22 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      10 3/12/2016 1:49:22 PM  4 Install-AllUpdates Restart needed. Creating startup task and rebooting.                              
      11 3/12/2016 1:49:27 PM 61 New-PSTask         Task PSWU Install-AllUpdates (AtBoot) was created on T81                          
      12 3/12/2016 1:49:27 PM  4 Install-AllUpdates Restart commence NOW                                                              
      13 3/12/2016 2:06:16 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      14 3/12/2016 2:09:45 PM 52 Get-UpdateList     14 update(s) found in 28 seconds.                                                 
      15 3/12/2016 2:09:46 PM  6 Install-AllUpdates 14 update(s) will be installed. ...                                               
      16 3/12/2016 2:09:46 PM 27 Install-Update     14 eligible updates found. ...                                                    
      17 3/12/2016 2:11:59 PM 29 Install-Update     Downloaded successfully; beginning install of 14 updates                          
      18 3/12/2016 2:20:43 PM 31 Install-Update     Installed updates with errors.                                                    
      19 3/12/2016 2:20:43 PM 33 Install-Update     Updates installed; please reboot soon.                                            
      20 3/12/2016 2:20:44 PM  7 Install-AllUpdates Returning to start.                                                               
      21 3/12/2016 2:20:44 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      22 3/12/2016 2:20:44 PM  4 Install-AllUpdates Restart needed. Creating startup task and rebooting.                              
      23 3/12/2016 2:20:46 PM 61 New-PSTask         Task PSWU Install-AllUpdates (AtBoot) was created on T81                          
      24 3/12/2016 2:20:46 PM  4 Install-AllUpdates Restart commence NOW                                                              
      25 3/12/2016 2:22:49 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      26 3/12/2016 2:26:19 PM 52 Get-UpdateList     1 update(s) found in 27 seconds.                                                  
      27 3/12/2016 2:26:20 PM  6 Install-AllUpdates 1 update(s) will be installed. ...                                                
      28 3/12/2016 2:26:21 PM 27 Install-Update     1 eligible updates found. ...                                                     
      29 3/12/2016 2:39:05 PM 29 Install-Update     Downloaded successfully; beginning install of 1 updates                           
      30 3/12/2016 2:51:20 PM 30 Install-Update     Installer error -2145124318, resultcode 4See https://support.microsoft.com/en-u...
      31 3/12/2016 2:51:21 PM 31 Install-Update     Installer error -2145124318, resultcode 4See https://support.microsoft.com/en-u...
      32 3/12/2016 2:51:21 PM 34 Install-Update     Updates installed; reboot NOT needed.                                             
      33 3/12/2016 2:51:21 PM  7 Install-AllUpdates Returning to start.                                                               
      34 3/12/2016 2:51:21 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      35 3/12/2016 2:51:32 PM 52 Get-UpdateList     1 update(s) found in 10 seconds.                                                  
      36 3/12/2016 2:51:32 PM  6 Install-AllUpdates 1 update(s) will be installed. ...                                                
      37 3/12/2016 2:51:32 PM 27 Install-Update     1 eligible updates found. ...                                                     
      38 3/12/2016 2:51:33 PM 29 Install-Update     Downloaded successfully; beginning install of 1 updates                           
      39 3/12/2016 2:51:34 PM 31 Install-Update     Installed updates successfully.                                                   
      40 3/12/2016 2:51:34 PM 33 Install-Update     Updates installed; please reboot soon.                                            
      41 3/12/2016 2:51:36 PM  7 Install-AllUpdates Returning to start.                                                               
      42 3/12/2016 2:51:36 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      43 3/12/2016 2:51:36 PM  4 Install-AllUpdates Restart needed. Creating startup task and rebooting.                              
      44 3/12/2016 2:51:37 PM 61 New-PSTask         Task PSWU Install-AllUpdates (AtBoot) was created on T81                          
      45 3/12/2016 2:51:37 PM  4 Install-AllUpdates Restart commence NOW                                                              
      46 3/12/2016 2:52:49 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      47 3/12/2016 2:52:49 PM  4 Install-AllUpdates Restart needed. Creating startup task and rebooting.                              
      48 3/12/2016 2:52:50 PM 61 New-PSTask         Task PSWU Install-AllUpdates (AtBoot) was created on T81                          
      49 3/12/2016 2:52:50 PM  4 Install-AllUpdates Restart commence NOW                                                              
      50 3/12/2016 2:53:43 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
      51 3/12/2016 2:53:43 PM  4 Install-AllUpdates Restart needed. Creating startup task and rebooting.                              
      52 3/12/2016 2:53:43 PM 61 New-PSTask         Task PSWU Install-AllUpdates (AtBoot) was created on T81                          
      53 3/12/2016 2:53:44 PM  4 Install-AllUpdates Restart commence NOW   

    ---- the restart loop continues for another ~145 iterations ----

     634 3/12/2016 5:06:21 PM  2 Install-AllUpdates Starting locally with params: -Computername t81  ...                              
     635 3/12/2016 5:06:46 PM 52 Get-UpdateList     2 update(s) found in 23 seconds.                                                  
     636 3/12/2016 5:06:47 PM  6 Install-AllUpdates 2 update(s) will be installed. ...                                                
     637 3/12/2016 5:06:47 PM 20 Install-Update     t81 pending reboot status is: .True. - please reboot before applying further up...
```

**Comment by bklockwood** [comment]
So there are several fixable issues here, in priority order:
1. [x] Win10 Upgrade being installed when the intention was to skip it. (#49)
2. [x] Reboot loops should be detected and stopped. (#51)
3. [x] The erroneous 'updates installed' message at recordid 32 (#47)
4. [x] Improper decimal to hex conversion at recordid 30, 31 (#46)
5. [x] Better logging all around. (#48)
